services:
  - type: web
    name: qr-manager-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: SHEET_ID
        value: 1h_fEz5tDjNmdZ-57F2CoL5W6RjjAF7Yhw4ttJgypb7o
      - key: DRIVE_FOLDER_ID
        value: 1STky8uJP19p1F7mfkiPrQE5jq4yOY_no
